exercise_dir: &exercise_dir
  working_directory: ~/project/exercises

version: 2.1
jobs:
  build:
    docker:
      - image: node:12
    steps:
      - checkout
      - run:
          command: npm install
          <<: *exercise_dir
      - run:
          command: npm run ch11
          <<: *exercise_dir
      - run:
          command: npm run lint
          <<: *exercise_dir
